"""first

Revision ID: d19a917769e6
Revises: 
Create Date: 2025-09-18 15:34:40.433831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19a917769e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registration_id', sa.String(length=255), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('resume_extracted_text', sa.Text(), nullable=False),
    sa.Column('resume_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('upk_eligible', sa.Boolean(), nullable=True),
    sa.Column('teacher_eligible', sa.Boolean(), nullable=True),
    sa.Column('substitute_eligible', sa.Boolean(), nullable=True),
    sa.Column('shift_available', sa.Boolean(), nullable=True),
    sa.Column('diaper_comfortable', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('work_experience_summary', sa.Text(), nullable=True),
    sa.Column('position_type', sa.String(length=100), nullable=True),
    sa.Column('school_type', sa.String(length=100), nullable=True),
    sa.Column('hr_review', sa.String(length=50), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('question_by_user_to_hr', sa.Text(), nullable=True),
    sa.Column('hr_answer_to_user', sa.Text(), nullable=True),
    sa.Column('resume_comparison', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_interview_registrations_id'), 'interview_registrations', ['id'], unique=False)
    op.create_table('question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_answered', sa.Boolean(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['interview_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_answers_id'), 'question_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_answers_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_interview_registrations_id'), table_name='interview_registrations')
    op.drop_table('interview_registrations')
    # ### end Alembic commands ###
